#!/usr/bin/env python
# encoding: utf-8
"""
shell_missing_method

Created by Matthew Trentacoste on 2010-10-19.
Copyright (c) 2010 matttrent.com. All rights reserved.
"""

import sys
import os


def main():
    print 'args:', sys.argv[1:]


if __name__ == '__main__':
    main()
